version: "3"

networks:
  traefik-net:
    external: true

services:
  website:
    image: registry.popcube.xyz:5000/popcube_website:latest
    deploy:
      labels:
        traefik.port: "80"
        traefik.frontend.rule: "Host:popcube.xyz"
        traefik.backend.loadbalancer.sticky: "true"
        traefik.backend.loadbalancer.swarm: "true"
        traefik.docker.network: "traefik-net"
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.10'
          memory: 20M
